using Autonotki.Application.DTOs;
using Autonotki.Client.Services;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace Autonotki.Client.ViewModels;

using System.ComponentModel;
using System.Linq;

public partial class DodajZlecenieViewModel : ViewModelBase, INotifyDataErrorInfo
{
    private readonly ApiService _api;
    private readonly MainWindowViewModel _main;
    public TopNavBarViewModel NavVM { get; }

    [ObservableProperty] private string _marka = "";
    [ObservableProperty] private string _model = "";
    [ObservableProperty] private string _rokProdukcji = "";
    [ObservableProperty] private string _vIN = "";
    [ObservableProperty] private string _typNadwozia = "";
    [ObservableProperty] private string _kolor = "";
    [ObservableProperty] private string _rodzajNaprawy = "";
    [ObservableProperty] private string _terminRealizacji = "";
    [ObservableProperty] private string _szacunkowyKoszt = "";
    [ObservableProperty] private string _miejscowosc = "";
    [ObservableProperty] private string _imieNazwisko = "";
    [ObservableProperty] private string _adres = "";
    [ObservableProperty] private string _telefon = "";

    public DodajZlecenieViewModel(ApiService api, MainWindowViewModel main)
    {
        _api = api; _main = main;
        NavVM = new TopNavBarViewModel(main);
    }
    // Validation state
    private readonly Dictionary<string, List<string>> _errors = new();
    public bool HasErrors => _errors.Any();
    public event EventHandler<DataErrorsChangedEventArgs>? ErrorsChanged;

    private void RaiseErrorsChanged(string propertyName) => ErrorsChanged?.Invoke(this, new DataErrorsChangedEventArgs(propertyName));

    // Expose first-line error and has-error flag for bindings
    public string ImieNazwiskoError => _errors.TryGetValue(nameof(ImieNazwisko), out var e) ? string.Join("\n", e) : string.Empty;
    public bool ImieNazwiskoHasError => !string.IsNullOrEmpty(ImieNazwiskoError);

    public string MarkaError => _errors.TryGetValue(nameof(Marka), out var e2) ? string.Join("\n", e2) : string.Empty;
    public bool MarkaHasError => !string.IsNullOrEmpty(MarkaError);

    public string ModelError => _errors.TryGetValue(nameof(Model), out var e3) ? string.Join("\n", e3) : string.Empty;
    public bool ModelHasError => !string.IsNullOrEmpty(ModelError);

    public string RokProdukcjiError => _errors.TryGetValue(nameof(RokProdukcji), out var e4) ? string.Join("\n", e4) : string.Empty;
    public bool RokProdukcjiHasError => !string.IsNullOrEmpty(RokProdukcjiError);

    public string TelefonError => _errors.TryGetValue(nameof(Telefon), out var e5) ? string.Join("\n", e5) : string.Empty;
    public bool TelefonHasError => !string.IsNullOrEmpty(TelefonError);

    public System.Collections.IEnumerable GetErrors(string? propertyName)
    {
        if (propertyName is null) return _errors.SelectMany(kv => kv.Value);
        return _errors.TryGetValue(propertyName, out var list) ? list : Array.Empty<string>();
    }

    private void ValidateProperty(string propertyName, string? value)
    {
        _errors.Remove(propertyName);
        var list = new List<string>();
        if (string.IsNullOrWhiteSpace(value))
            list.Add("Pole jest wymagane.");

        if (propertyName == nameof(RokProdukcji) && !string.IsNullOrWhiteSpace(value))
        {
            if (!int.TryParse(value, out var yr) || yr < 1886 || yr > DateTime.Now.Year + 1)
                list.Add("Podaj poprawny rok produkcji.");
        }

        if (propertyName == nameof(Telefon) && !string.IsNullOrWhiteSpace(value))
        {
            // Basic phone validation (digits, + and spaces)
            var cleaned = new string(value.Where(c => char.IsDigit(c) || c == '+').ToArray());
            if (cleaned.Length < 6)
                list.Add("Podaj poprawny numer telefonu.");
        }

        if (list.Count > 0)
            _errors[propertyName] = list;
        else
            _errors.Remove(propertyName);

        RaiseErrorsChanged(propertyName);
        // notify computed error properties
        OnPropertyChanged(propertyName + "Error");
        OnPropertyChanged(propertyName + "HasError");
    }

    // Partial methods generated by CommunityToolkit when using [ObservableProperty]
    partial void OnImieNazwiskoChanged(string value) => ValidateProperty(nameof(ImieNazwisko), value);
    partial void OnMarkaChanged(string value) => ValidateProperty(nameof(Marka), value);
    partial void OnModelChanged(string value) => ValidateProperty(nameof(Model), value);
    partial void OnRokProdukcjiChanged(string value) => ValidateProperty(nameof(RokProdukcji), value);
    partial void OnTelefonChanged(string value) => ValidateProperty(nameof(Telefon), value);

    bool INotifyDataErrorInfo.HasErrors => HasErrors;

    [RelayCommand]
    public async Task Save()
    {
        // Trigger validation for required properties
        ValidateProperty(nameof(ImieNazwisko), ImieNazwisko);
        ValidateProperty(nameof(Marka), Marka);
        ValidateProperty(nameof(Model), Model);
        ValidateProperty(nameof(RokProdukcji), RokProdukcji);
        ValidateProperty(nameof(Telefon), Telefon);

        if (HasErrors)
            return;

        var req = new CreateZlecenieRequest(
            Marka, Model, RokProdukcji, VIN, TypNadwozia, Kolor,
            RodzajNaprawy, TerminRealizacji, SzacunkowyKoszt,
            ImieNazwisko, Miejscowosc, Adres, Telefon);
        await _api.CreateZlecenieAsync(req);
        _main.NavigateToPrzegladaj();
    }
}
